# Generated by Django 5.0.6 on 2024-09-08 19:55

from django.db import migrations
from django.conf import settings

def create_missing_customer_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Customer = apps.get_model('profiles', 'Customer')
    
    for user in User.objects.filter(user_role=settings.K_CUSTOMER_USER_ROLE):
        Customer.objects.get_or_create(user=user)

def reverse_func(apps, schema_editor):
    # No need to do anything for reverse migration
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_missing_customer_profiles, reverse_func),
    ]
