# Generated by Django 5.0.6 on 2024-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'MANAGER'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=20, null=True),
        ),
    ]
