# Generated by Django 5.0.6 on 2024-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customer_user_remove_productmanager_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
