# Generated by Django 5.0.6 on 2024-06-14 09:09

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
