# Generated by Django 5.0.6 on 2024-08-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_categories'),
        ('shop_settings', '0002_customfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='shop_settings.customfield')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'field')},
            },
        ),
    ]
