# Generated by Django 5.0.6 on 2024-08-29 07:07

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_customfielddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
