# Generated by Django 5.0.6 on 2024-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_sold',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
