# Generated by Django 5.0.6 on 2024-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_custom_stock_out_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
