# Generated by Django 5.0.6 on 2024-06-04 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_title_remove_blogpost_title_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='temp_title',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
