# Generated by Django 5.0.6 on 2024-06-04 07:08

from django.db import migrations, models
import uuid


def populate_uuid_field(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    for post in BlogPost.objects.all():
        post.temp_title = uuid.uuid4()
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_temp_title'),
    ]

    operations = [
        migrations.RunPython(populate_uuid_field)
    ]
