# Generated by Django 5.0.6 on 2024-06-04 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240604_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='temp_title',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
