# Generated by Django 5.0.6 on 2024-06-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_temp_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
