# Generated by Django 5.0.6 on 2024-06-04 07:23

from django.db import migrations


def populate_title_en_field(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    for post in BlogPost.objects.all():
        post.title_en = str(post.temp_title)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_title_en'),
    ]

    operations = [
        migrations.RunPython(populate_title_en_field)
    ]
