# Generated by Django 5.0.6 on 2024-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20240604_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
