# Generated by Django 5.0.6 on 2024-06-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='temp_title',
        ),
    ]
