# Generated by Django 5.0.6 on 2024-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blogpost_temp_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
