# Generated by Django 5.0.6 on 2024-06-04 07:28

from django.db import migrations
import uuid


def populate_slug_field(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    for post in BlogPost.objects.all():
        post.slug = str(uuid.uuid4())
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogpost_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug_field)
    ]
