# Generated by Django 5.0.6 on 2024-06-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_blogpost_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
