# Generated by Django 5.0.6 on 2024-08-27 07:05

from django.db import migrations, models


def transfer_data(apps, schema_editor):
    OldCategory = apps.get_model('product', 'Category')
    NewCategory = apps.get_model('shop_settings', 'Category')
    
    for old_cat in OldCategory.objects.all():
        NewCategory.objects.create(
            id=old_cat.id,
            title=old_cat.title,
            image=old_cat.image,
            description=old_cat.description,
            created_at=old_cat.created_at,
            updated_at=old_cat.updated_at
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/categories/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(transfer_data),
    ]
